version: '3.8'

services:
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_server1
      - app_server2
    networks:
      - app-network

  app_server1:
      build: ./app_server
      ports:
        - "5001:91"
      volumes:
        - ./app_server/s1:/var/www/html
        - ./csr:/home/csr
        - ./cert:/home/cert
        - ./key:/home/key
        - ./CA_cert:/home/CA_cert
        - ./p12:/home/p12
      networks: 
        - app-network

  app_server2:
      build: ./app_server
      ports:
        - "5002:92"
      volumes:
        - ./app_server/s2:/var/www/html
        - ./csr:/home/csr
        - ./cert:/home/cert
        - ./key:/home/key
        - ./CA_cert:/home/CA_cert
        - ./p12:/home/p12
      networks: 
        - app-network
        
  web_server-app:
      build: ./web_server
      ports:
        - "8080:81"
      volumes:
        - ./web_server/app:/var/www/html
        - ./csr:/home/csr
        - ./cert:/home/cert
        - ./key:/home/key
        - ./CA_cert:/home/CA_cert
        - ./p12:/home/p12
      networks: 
        - app-network

  #mysql
  database:
      container_name: coresign_db
      image: mysql:8.0
      restart: unless-stopped
      tty: true
      environment: 
          MYSQL_DATABASE: coresign
          MYSQL_ROOT_PASSWORD: karyakampak
          MYSQL_USER: karyadidk
          MYSQL_PASSWORD: karyakampak
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
          TZ: Asia/Jakarta
      volumes: 
          - ./dbdata/mysql:/var/lib/mysql
          # - ./docker/container/my.cnf:/etc/mysql/my.cnf
          # - ./docker/container/mysql/log:/var/log/mysql
      ports: 
          - "3307:3306"
      networks: 
        - app-network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: coresign_pma
      links:
        - database
      environment:
          PMA_HOST: coresign_db
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - 8081:80
      networks: 
        - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
